// lang.js – AgriPredict Multilingual Support (English, Hindi, Telugu)

const TRANSLATIONS = {
  en: {
    brand: 'AgriPredict',
    marketplace: '🛒 Marketplace',
    dashboard: '📊 Dashboard',
    helpCenter: '🆘 Help Center',
    greeting: '👨‍🌾 Welcome, Farmer',
    logout: '🚪 Logout',
    overview: '📊 Overview',
    myProducts: '🌾 My Products',
    addProduct: '➕ Add Product',
    orders: '📦 Orders',
    aiPrediction: '🤖 AI Prediction',
    heroTitle: 'Empowering Farmers with AI Intelligence',
    heroSub: 'Direct marketplace, AI price predictions, and weather insights to help you grow more.',
    browseBtn: '🛍️ Browse Crops',
    sellBtn: '👨‍🌾 Sell as Farmer',
    farmers: 'Farmers',
    savings: 'Price Savings',
    delivery: 'Fresh Delivery',
    availableCrops: 'Available Crops',
    filterAll: 'All',
    filterGrains: 'Grains',
    filterVegetables: 'Vegetables',
    filterPulses: 'Pulses',
    whyTitle: 'Why AgriPredict?',
    noMiddlemen: 'No Middlemen',
    noMiddlemenDesc: 'Farmers sell directly to buyers, keeping more of the profit.',
    fairPrices: 'Fair Prices',
    fairPricesDesc: 'Real market prices based on demand and seasonality.',
    freshProduce: 'Fresh Produce',
    freshProduceDesc: 'All products are harvested within 48 hours of listing.',
    cartTitle: 'Your Cart',
    placeOrder: 'Place Order',
    total: 'Total:',
    orderTitle: '📦 Place Your Order',
    nameLbl: 'Your Name',
    emailLbl: 'Email Address',
    phoneLbl: 'Phone Number',
    addressLbl: 'Delivery Address',
    sendOrder: '✅ Send Order Request',
    whatsappOrder: '💬 Order via WhatsApp',
    dashTitle: 'Dashboard Overview',
    activeProducts: 'Active Products',
    ordersReceived: 'Orders Received',
    estRevenue: 'Est. Revenue',
    recentOrders: 'Recent Orders',
    noOrders: 'No orders yet. Share your products to get started! 🌾',
    mandiInsights: '📊 Mandi Market Insights',
    priceTrends: '📉 Price Trends (Last 6 Months)',
    actionableIntel: '💡 Actionable Intelligence',
    addProductTitle: 'Add New Product',
    cropName: 'Crop / Product Name',
    category: 'Category',
    priceUnit: 'Price per Unit (₹)',
    unit: 'Unit',
    description: 'Description',
    location: 'Your Location',
    contactPhone: 'Contact Phone',
    imageUrl: 'Product Image URL',
    listProduct: '✅ List Product',
    aiTitle: '🤖 AI Price Prediction',
    aiSubtitle: 'Enter your crop details to get AI-powered price forecasts based on seasonal trends.',
    cropType: 'Crop Type',
    monthLabel: 'Month (1–12)',
    stateLabel: 'Your State',
    predictBtn: '🔮 Predict Price',
    predictionResult: 'Prediction Result',
    forecast: '📅 6-Month AI Forecast',
    harvestTime: 'Harvest time!',
    orderSuccess: '✅ Order sent! Farmer will contact you soon.',
    footer: '© 2024 AgriPredict. Empowering farmers across India.',
    govtSchemes: '🏛️ Govt Schemes',
    cropDoctor: '🔬 Crop Doctor',
    cropCalendar: '📅 Crop Calendar',
    calculators: '🧮 Calculator',
    helplines: '📞 Helplines',
    farmingTips: '💡 Farming Tips',
    helpTitle: '🌾 Farmer Help Center',
    helpSub: 'Everything you need — government schemes, crop health, farming calendar, and emergency contacts.',
  },
  hi: {
    brand: 'एग्रीप्रेडिक्ट',
    marketplace: '🛒 बाज़ार',
    dashboard: '📊 डैशबोर्ड',
    helpCenter: '🆘 सहायता केंद्र',
    greeting: '👨‍🌾 स्वागत, किसान',
    logout: '🚪 लॉग आउट',
    overview: '📊 अवलोकन',
    myProducts: '🌾 मेरे उत्पाद',
    addProduct: '➕ उत्पाद जोड़ें',
    orders: '📦 ऑर्डर',
    aiPrediction: '🤖 AI भविष्यवाणी',
    heroTitle: 'AI तकनीक से किसानों को सशक्त बनाना',
    heroSub: 'सीधा बाज़ार, AI मूल्य भविष्यवाणी और मौसम की जानकारी — ज़्यादा मुनाफ़ా कमाएं।',
    browseBtn: '🛍️ फसलें देखें',
    sellBtn: '👨‍🌾 किसान के रूप में बेचें',
    farmers: 'किसान',
    savings: 'मूल्य बचत',
    delivery: 'ताज़ी डिलीवरी',
    availableCrops: 'उपलब्ध फसलें',
    filterAll: 'सभी',
    filterGrains: 'अनाज',
    filterVegetables: 'सब्जियाँ',
    filterPulses: 'दालें',
    whyTitle: 'एग्रीप्रेडिक्ट क्यों?',
    noMiddlemen: 'कोई बिचौलिया नहीं',
    noMiddlemenDesc: 'किसान सीधे खरीदारों को बेचते हैं, ज़्यादा मुनाफ़ా कमाते हैं।',
    fairPrices: 'उचित मूल्य',
    fairPricesDesc: 'మాంగ్ మరియు మాసమ్ కే ఆధార పర్ వాస్తవిక్ బాజార్ భావ్।',
    freshProduce: 'తాజీ ఉపజ్',
    freshProduceDesc: 'సభీ ఉత్పాద లిస్టింగ్ కే 48 ఘంటే కే భీతర్ కాటే గయే హై।',
    cartTitle: 'आपकी टोकरी',
    placeOrder: 'ऑर्डर दें',
    total: 'कुल:',
    orderTitle: '📦 अपना ऑर्डर दें',
    nameLbl: 'आपका नाम',
    emailLbl: 'ईमेल पता',
    phoneLbl: 'फोन नंबर',
    addressLbl: 'డిలీవరీ పతా',
    sendOrder: '✅ ఆర్డర్ అనురోధ్ భేజే',
    whatsappOrder: '💬 WhatsApp పర్ ఆర్డర్ కరే',
    dashTitle: 'డ్యాష్ బోర్డ్ అవలోకన్',
    activeProducts: 'సక్రియ ఉత్పాద',
    ordersReceived: 'ప్రాప్త ఆర్డర్',
    estRevenue: 'అనుమానిత్ ఆయ',
    recentOrders: 'హాల్ కే ఆర్డర్',
    noOrders: 'అభీ కోయి ఆర్డర్ నహీ। అపనే ఉత్పాద సాఝా కరే! 🌾',
    mandiInsights: '📊 మండి బాజార్ జానకారీ',
    priceTrends: '📉 మూల్య రుఝాన్ (పిఛలే 6 మహీనే)',
    actionableIntel: '💡 కార్రవాయి యోగ్య జానకారీ',
    addProductTitle: 'నయా ఉత్పాద జోడే',
    cropName: 'ఫసల్ / ఉత్పాద కా నామ్',
    category: 'శ్రేణీ',
    priceUnit: 'ప్రతి ఇకాయి మూల్య (₹)',
    unit: 'ఇకాయి',
    description: 'వివరణ',
    location: 'ఆపకా స్థాన్',
    contactPhone: 'సంపర్క్ ఫోన్',
    imageUrl: 'ఉత్పాద ఛవి URL',
    listProduct: '✅ ఉత్పాద సూచీబద్ధ కరే',
    aiTitle: '🤖 AI మూల్య భవిష్యవాణీ',
    aiSubtitle: 'మౌసమీ రుఝానో కే ఆధార్ పర్ AI-సంచాలిత్ మూల్య పూర్వానుమాన్ పానే కే లియే ఫసల్ కా వివరణ దర్జ్ కరే।',
    cropType: 'ఫసల్ కా ప్రకార్',
    monthLabel: 'మహీనా (1–12)',
    stateLabel: 'ఆపకా రాజ్య',
    predictBtn: '🔮 మూల్య భవిష్యవాణీ కరే',
    predictionResult: 'భవిష్యవాణీ పరిణామ',
    forecast: '📅 6-మాహ AI పూర్వానుమాన్',
    harvestTime: 'కటాయి కా సమయ!',
    orderSuccess: '✅ ఆర్డర్ భేజా గయా! కిసాన్ జల్ద్ సంపర్క్ కరేగా।',
    footer: '© 2024 ఏగ్రీప్రెడిక్ట్। పూరే భారత్ మే కిసానో కో సశక్త బనానా।',
    govtSchemes: '🏛️ ప్రభుత్వ యోజనాయే',
    cropDoctor: '🔬 ఫసల్ డాక్టర్',
    cropCalendar: '📅 ఫసల్ క్యాలెండర్',
    calculators: '🧮 క్యాలిక్యులేటర్',
    helplines: '📞 హెల్ప్‌లైన్',
    farmingTips: '💡 ఖేతీ కే టిప్స్',
    helpTitle: '🌾 కిసాన్ సహాయతా కేంద్ర',
    helpSub: 'సరకారీ యోజనాయే, ఫసల్ స్వాస్థ్య, ఖేతీ క్యాలెండర్ ఔర్ ఆపాత్కాలీన్ సంపర్క్ — సబ్ కుచ్ ఏక్ హీ స్థాన్ పర్।',
  },
  te: {
    brand: 'అగ్రిప్రెడిక్ట్',
    marketplace: '🛒 మార్కెట్ ప్లేస్',
    dashboard: '📊 డాష్ బోర్డ్',
    helpCenter: '🆘 సహాయ కేంద్రం',
    greeting: '👨‍🌾 స్వాగతం, రైతు',
    logout: '🚪 లాగ్ అవుట్',
    overview: '📊 అవలోకనం',
    myProducts: '🌾 నా ఉత్పత్తులు',
    addProduct: '➕ ఉత్పత్తిని జోడించు',
    orders: '📦 ఆర్డర్లు',
    aiPrediction: '🤖 AI అంచనా',
    heroTitle: 'AI పరిజ్ఞానంతో రైతులకు సాధికారత',
    heroSub: 'నేరుగా మార్కెట్ ప్లేస్, AI ధరల అంచనాలు మరియు వాతావరణ సమాచారంతో మీ ఆదాయాన్ని పెంచుకోండి.',
    browseBtn: '🛍️ పంటలను చూడండి',
    sellBtn: '👨‍🌾 రైతుగా అమ్మండి',
    farmers: 'రైతులు',
    savings: 'ధర పొదుపు',
    delivery: 'తాజా డెలివరీ',
    availableCrops: 'అందుబాటులో ఉన్న పంటలు',
    filterAll: 'అన్నీ',
    filterGrains: 'ధాన్యాలు',
    filterVegetables: 'కూరగాయలు',
    filterPulses: 'పప్పుధాన్యాలు',
    whyTitle: 'ఎందుకు అగ్రిప్రెడిక్ట్?',
    noMiddlemen: 'దళారులు లేరు',
    noMiddlemenDesc: 'రైతులు నేరుగా కొనుగోలుదారులకు అమ్ముతారు, లాభం మీకే.',
    fairPrices: 'న్యాయమైన ధరలు',
    fairPricesDesc: 'డిమాండ్ మరియు సీజన్ ఆధారంగా నిజమైన మార్కెట్ ధరలు.',
    freshProduce: 'తాజా దిగుబడి',
    freshProduceDesc: 'అన్ని ఉత్పత్తులు కోత కోసిన 48 గంటల్లోనే లిస్ట్ చేయబడతాయి.',
    cartTitle: 'మీ కార్ట్',
    placeOrder: 'ఆర్డర్ చేయండి',
    total: 'మొత్తం:',
    orderTitle: '📦 మీ ఆర్డర్ ప్లేస్ చేయండి',
    nameLbl: 'మీ పేరు',
    emailLbl: 'ఈమెయిల్ చిరునామా',
    phoneLbl: 'ఫోన్ నంబర్',
    addressLbl: 'డెలివరీ చిరునామా',
    sendOrder: '✅ ఆర్డర్ అభ్యర్థన పంపండి',
    whatsappOrder: '💬 వాట్సాప్ ద్వారా ఆర్డర్',
    dashTitle: 'డాష్ బోర్డ్ అవలోకనం',
    activeProducts: 'యాక్టివ్ ఉత్పత్తులు',
    ordersReceived: 'వచ్చిన ఆర్డర్లు',
    estRevenue: 'అంచనా ఆదాయం',
    recentOrders: 'ఇటీవలి ఆర్డర్లు',
    noOrders: 'ఇంకా ఆర్డర్లు లేవు. మీ ఉత్పత్తులను షేర్ చేయండి! 🌾',
    mandiInsights: '📊 మార్కెట్ సమాచారం',
    priceTrends: '📉 ధరల ధోరణి (గత 6 నెలలు)',
    actionableIntel: '💡 ముఖ్యమైన సమాచారం',
    addProductTitle: 'కొత్త ఉత్పత్తిని జోడించు',
    cropName: 'పంట / ఉత్పత్తి పేరు',
    category: 'వర్గం',
    priceUnit: 'యూనిట్ ధర (₹)',
    unit: 'యూనిట్',
    description: 'వివరణ',
    location: 'మీ ప్రాంతం',
    contactPhone: 'సంప్రదింపు ఫోన్',
    imageUrl: 'ఉత్పత్తి చిత్రం URL',
    listProduct: '✅ ఉత్పత్తిని లిస్ట్ చేయండి',
    aiTitle: '🤖 AI ధరల అంచనా',
    aiSubtitle: 'సీజనల్ ధోరణుల ఆధారంగా AI ద్వారా ధరల అంచనాలను పొందడానికి మీ పంట వివరాలను నమోదు చేయండి.',
    cropType: 'పంట రకం',
    monthLabel: 'నెల (1–12)',
    stateLabel: 'మీ రాష్ట్రం',
    predictBtn: '🔮 ధరను అంచనా వేయండి',
    predictionResult: 'అంచనా ఫలితం',
    forecast: '📅 6 నెలల AI అంచనా',
    harvestTime: 'కోత సమయం!',
    orderSuccess: '✅ ఆర్డర్ పంపబడింది! రైతు మిమ్మల్ని త్వరలో సంప్రదిస్తారు.',
    footer: '© 2024 అగ్రిప్రెడిక్ట్. భారతీయ రైతులకు అండగా.',
    govtSchemes: '🏛️ ప్రభుత్వ పథకాలు',
    cropDoctor: '🔬 క్రాప్ డాక్టర్',
    cropCalendar: '📅 పంట క్యాలెండర్',
    calculators: '🧮 కాలిక్యులేటర్',
    helplines: '📞 హెల్ప్‌లైన్లు',
    farmingTips: '💡 వ్యవసాయ చిట్కాలు',
    helpTitle: '🌾 రైతు సహాయ కేంద్రం',
    helpSub: 'ప్రభుత్వ పథకాలు, పంటల ఆరోగ్యం, వ్యవసాయ క్యాలెండర్ మరియు అత్యవసర సంప్రదింపులు — అన్నీ ఒకే చోట.',
  }
};

let currentLang = localStorage.getItem('agri_lang') || 'en';

function t(key) {
  return TRANSLATIONS[currentLang][key] || TRANSLATIONS['en'][key] || key;
}

function applyTranslations() {
  document.querySelectorAll('[data-t]').forEach(el => {
    const key = el.getAttribute('data-t');
    const translation = t(key);
    if (!translation) return;

    if (el.innerHTML.includes('<span') || el.innerHTML.includes('Emoji') || el.childNodes.length > 1) {
        // Handle complex innerHTML (preserve icons/emojis)
        const emoji = el.innerHTML.match(/^(?:[\u2700-\u27bf]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff]|[\u0023-\u0039]\ufe0f?\u20e3|\u3299|\u3297|\u303d|\u3030|\u24c2|\ud83c[\udd70-\udd71]|\ud83c[\udd7e-\udd7f]|\ud83c\udd8e|\ud83c[\udd91-\udd9a]|\ud83c[\udde6-\uddff]|\ud83c[\ude01-\ude02]|\ud83c\ude1a|\ud83c\ude2f|\ud83c[\ude32-\ude3a]|\ud83c[\ude50-\ude51]|\u203c|\u2049|\u2139|[\u2194-\u2199]|[\u21a9-\u21aa]|\u231a|\u231b|\u2328|\u23cf|[\u23e9-\u23f3]|[\u23f8-\u23fa]|\u24c2|\ud83c[\udf00-\udfff]|\ud83d[\udc00-\udfff]|\ud83e[\udc00-\udfff])+/);
        const icon = emoji ? emoji[0] : '';
        const cleanT = translation.replace(/^(?:[\u2700-\u27bf]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff]|[\u0023-\u0039]\ufe0f?\u20e3|\u3299|\u3297|\u303d|\u3030|\u24c2|\ud83c[\udd70-\udd71]|\ud83c[\udd7e-\udd7f]|\ud83c\udd8e|\ud83c[\udd91-\udd9a]|\ud83c[\udde6-\uddff]|\ud83c[\ude01-\ude02]|\ud83c\ude1a|\ud83c\ude2f|\ud83c[\ude32-\ude3a]|\ud83c[\ude50-\ude51]|\u203c|\u2049|\u2139|[\u2194-\u2199]|[\u21a9-\u21aa]|\u231a|\u231b|\u2328|\u23cf|[\u23e9-\u23f3]|[\u23f8-\u23fa]|\u24c2|\ud83c[\udf00-\udfff]|\ud83d[\udc00-\udfff]|\ud83e[\udc00-\udfff])+\s*/, '');
        el.innerHTML = icon ? `${icon} ${cleanT}` : cleanT;
    } else {
        el.textContent = translation;
    }
  });

  document.querySelectorAll('[data-t-placeholder]').forEach(el => {
    const key = el.getAttribute('data-t-placeholder');
    const translation = t(key);
    if (translation) el.placeholder = translation;
  });

  document.documentElement.lang = currentLang;
  document.querySelectorAll('.lang-select').forEach(sel => sel.value = currentLang);
  document.dispatchEvent(new CustomEvent('langChange', { detail: { lang: currentLang } }));
}

function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('agri_lang', lang);
  applyTranslations();
}

document.addEventListener('DOMContentLoaded', applyTranslations);
